/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an object in the audit
    /// </summary>
    [Table("aud_obj_tbl")]
    public class DbAuditObject : DbAssociation
    {

        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("obj_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the audit the object is set to
        /// </summary>
        [Column("aud_id"), NotNull, ForeignKey(typeof(DbAudit), nameof(DbAudit.Key))]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the id of the object
        /// </summary>
        [Column("ext_id"), NotNull]
        public String ExternalId { get; set; }

        /// <summary>
        /// Gets or sets the type code
        /// </summary>
        [Column("typ_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid TypeCodeKey { get; set; }

        /// <summary>
        /// Gets or sets role code
        /// </summary>
        [Column("rol_cd_id"), ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid RoleCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the lifecycle
        /// </summary>
        [Column("lcycl_cd_id"), ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid LifecycleCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the id type code
        /// </summary>
        [Column("id_typ_cd_id"), ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid IdTypeCodeKey { get; set; }

    }
}
