using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an object in the audit
    /// </summary>
    [Table("aud_obj_tbl")]
    public class DbAuditObject : DbIdentified
    {

        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("obj_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the audit the object is set to
        /// </summary>
        [Column("aud_id"), NotNull, ForeignKey(typeof(DbAudit), nameof(DbAudit.Key))]
        public Guid AuditKey { get; set; }

        /// <summary>
        /// Gets or sets the id of the object
        /// </summary>
        [Column("ext_id"), NotNull]
        public String ExternalId { get; set; }

        /// <summary>
        /// Gets or sets the type code
        /// </summary>
        [Column("typ_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid TypeCodeKey { get; set; }

        /// <summary>
        /// Gets or sets role code
        /// </summary>
        [Column("rol_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid RoleCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the lifecycle
        /// </summary>
        [Column("lcycl_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid LifecycleCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the id type code
        /// </summary>
        [Column("id_typ_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid IdTypeCodeKey { get; set; }

    }
}
