/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents a version of an audit
    /// </summary>
    [Table("aud_vrsn_tbl")]
    public class DbAuditVersion : DbVersionedData
    {

        /// <summary>
        /// Gets or sets the audit version id
        /// </summary>
        [NotNull, Column("aud_id"), ForeignKey(typeof(DbAudit), nameof(DbAudit.Key)), AlwaysJoin]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the related audit
        /// </summary>
        [AutoGenerated, PrimaryKey, Column("aud_vrsn_id")]
        public override Guid VersionKey { get; set; }

        /// <summary>
        /// Gets or sets the previous version
        /// </summary>
        [ForeignKey(typeof(DbAuditVersion), nameof(Key))]
        public Guid? PreviousVersionKey { get; set; }

        /// <summary>
        /// Gets or sets the audit code
        /// </summary>
        [Column("sts_cd_id"), NotNull]
        public int Status { get; set; }
        
        /// <summary>
        /// Gets or sets the alert indicator
        /// </summary>
        [Column("is_alrt"), NotNull]
        public bool IsAlert { get; set; }

    }
}
