/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an audit code
    /// </summary>
    [Table("aud_cd_tbl")]
    public class DbAuditCode : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [PrimaryKey, Column("cd_id"), AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or set sthe code
        /// </summary>
        [Column("mnemonic"), NotNull]
        public String Mnemonic { get; set; }

        /// <summary>
        /// Gets or sets the code system
        /// </summary>
        [Column("domain"), NotNull]
        public String Domain { get; set; }

        /// <summary>
        /// Gets or sets the display name
        /// </summary>
        [Column("display")]
        public String DisplayName { get; set; }
    }
}
