using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an audit source
    /// </summary>
    [Table("aud_src_tbl")]
    [AssociativeTable(typeof(DbAuditCode), typeof(DbAuditSourceType))]
    public class DbAuditSource : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [PrimaryKey, Column("aud_src_id"), AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the enterprise site id
        /// </summary>
        [Column("ent_ste_nam")]
        public String EnterpriseSiteId { get; set; }

        /// <summary>
        /// Gets or sets the audit source id
        /// </summary>
        [Column("aud_src_nam")]
        public String AuditSourceId { get; set; }
    }
}
