using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents a version of an audit
    /// </summary>
    [Table("aud_vrsn_tbl")]
    public class DbAuditVersion : DbBaseData
    {

        /// <summary>
        /// Gets or sets the audit version id
        /// </summary>
        [PrimaryKey, AutoGenerated, Column("aud_vrsn_id")]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the related audit
        /// </summary>
        [NotNull, Column("aud_id"), ForeignKey(typeof(DbAudit), nameof(DbAudit.Key))]
        public Guid AuditKey { get; set; }

        /// <summary>
        /// Gets or sets the previous version
        /// </summary>
        [Column("replc_vrsn_id"), ForeignKey(typeof(DbAuditVersion), nameof(Key))]
        public Guid? PreviousVersionKey { get; set; }

        /// <summary>
        /// Gets or sets the audit code
        /// </summary>
        [Column("sts_cd_id"), NotNull]
        public int StatusCode { get; set; }
        
        /// <summary>
        /// Gets or sets the alert indicator
        /// </summary>
        [Column("is_alrt"), NotNull]
        public bool IsAlert { get; set; }

    }
}
