using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an actor in the db for audits
    /// </summary>
    [Table("aud_ptcpt_tbl")]
    public class DbAuditParticipant : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key of the participant
        /// </summary>
        [Column("ptcpt_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the node key
        /// </summary>
        [Column("node_id"), ForeignKey(typeof(DbAuditNode), nameof(DbAuditNode.Key))]
        public Guid NodeKey { get; set; }

        /// <summary>
        /// Gets or sets the security identifier
        /// </summary>
        [Column("sid")]
        public Guid SecurityIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the user id
        /// </summary>
        [Column("usr_id")]
        public String UserIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the user name
        /// </summary>
        [Column("usr_name")]
        public String UserName { get; set; }

        /// <summary>
        /// Gets or sets the network access point
        /// </summary>
        [Column("net_ap")]
        public String NetworkAccessPoint { get; set; }

        /// <summary>
        /// Network access point type
        /// </summary>
        [Column("net_ap_typ")]
        public Int32 NetworkAccessPointType { get; set; }
    }
}
