/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an audit node in the database
    /// </summary>
    [Table("aud_node_tbl")]
    public class DbAuditNode : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("node_id"), AutoGenerated, NotNull, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the device
        /// </summary>
        [Column("dev_id")]
        public Guid? SecurityDeviceKey { get; set; }

        /// <summary>
        /// Gets or sets the name of the node
        /// </summary>
        [Column("name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the host name
        /// </summary>
        [Column("host_name")]
        public String HostName { get; set; }

        /// <summary>
        /// Gets or sets the status code
        /// </summary>
        [Column("sts_cd_id"), NotNull]
        public int Status { get; set; }
    }
}
