using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents the audit object detail
    /// </summary>
    [Table("aud_obj_dtl_tbl")]
    public class DbAuditObjectDetail : DbIdentified
    {

        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("dtl_id"), AutoGenerated, PrimaryKey, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the object key
        /// </summary>
        [Column("obj_id"), NotNull, ForeignKey(typeof(DbAuditObject), nameof(DbAuditObject.Key))]
        public Guid ObjectKey { get; set; }

        /// <summary>
        /// Gets or sets the detail type
        /// </summary>
        [Column("dtl_typ"), NotNull]
        public String DetailType { get; set; }

        /// <summary>
        /// Gets or sets the value
        /// </summary>
        [Column("dtl_val"), NotNull]
        public byte[] DetailValue { get; set; }
    }
}
