/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an audit in the database
    /// </summary>
    [Table("aud_tbl"), 
        AssociativeTable(typeof(DbAuditParticipant), typeof(DbAuditParticipantAuditAssociation)),
        AssociativeTable(typeof(DbAuditCode), typeof(DbAuditEventTypeAssociation))]
    public class DbAudit : DbIdentified
    {
        /// <summary>
        /// Gets or sets the primary key
        /// </summary>
        [Column("aud_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the correlation identifier
        /// </summary>
        [Column("corr_id"), NotNull]
        public Guid CorrelationToken { get; set; }

        /// <summary>
        /// Gets or sets the action code key
        /// </summary>
        [Column("act_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid ActionCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the outcome code
        /// </summary>
        [Column("out_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid OutcomeCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the action code
        /// </summary>
        [Column("evt_cd_id"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public Guid EventIdCodeKey { get; set; }

        /// <summary>
        /// Gets or sets the event time
        /// </summary>
        [Column("evt_utc"), NotNull]
        public DateTime EventTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the session key
        /// </summary>
        [Column("ses_id"), ForeignKey(typeof(DbAuditSession), nameof(DbAuditSession.Key))]
        public Guid SessionKey { get; set; }

        /// <summary>
        /// Gets or sets the process name
        /// </summary>
        [Column("ps_name")]
        public String ProcessName { get; set; }

        /// <summary>
        /// Gets or sets the process id
        /// </summary>
        [Column("ps_id")]
        public String ProcessId { get; set; }

        /// <summary>
        /// Gets or sets the audit source
        /// </summary>
        [Column("src_id"), ForeignKey(typeof(DbAuditSource), nameof(DbAuditSource.Key))]
        public Guid AuditSourceKey { get; set; }

    }
}
