/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents the audit object detail
    /// </summary>
    [Table("aud_obj_dtl_tbl")]
    public class DbAuditObjectDetail : DbAssociation
    {

        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("dtl_id"), AutoGenerated, PrimaryKey, NotNull]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the object key
        /// </summary>
        [Column("obj_id"), NotNull, ForeignKey(typeof(DbAuditObject), nameof(DbAuditObject.Key))]
        public override Guid SourceKey { get; set; }

        /// <summary>
        /// Gets or sets the detail type
        /// </summary>
        [Column("dtl_typ"), NotNull]
        public String DetailType { get; set; }

        /// <summary>
        /// Gets or sets the value
        /// </summary>
        [Column("dtl_val"), NotNull]
        public byte[] DetailValue { get; set; }
    }
}
