using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an audit in the database
    /// </summary>
    [Table("aud_tbl"), 
        AssociativeTable(typeof(DbAuditParticipant), typeof(DbAuditParticipantAuditAssociation)),
        AssociativeTable(typeof(DbAuditSource), typeof(DbAuditSourceAssociation))]

    public class DbAudit : DbIdentified
    {
        /// <summary>
        /// Gets or sets the primary key
        /// </summary>
        [Column("aud_id"), AutoGenerated, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the sequence
        /// </summary>
        [Column("aud_seq_id"), AutoGenerated, NotNull]
        public int Sequence { get; set; }

        /// <summary>
        /// Gets or sets the correlation identifier
        /// </summary>
        [Column("corr_id"), NotNull]
        public Guid CorrelationToken { get; set; }

        /// <summary>
        /// Gets or sets the action code key
        /// </summary>
        [Column("act_cs"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public int ActionCode { get; set; }

        /// <summary>
        /// Gets or sets the outcome code
        /// </summary>
        [Column("out_cs"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public int Outcome { get; set; }

        /// <summary>
        /// Gets or sets the action code
        /// </summary>
        [Column("typ_cs"), NotNull, ForeignKey(typeof(DbAuditCode), nameof(DbAuditCode.Key))]
        public int EventIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the event time
        /// </summary>
        [Column("evt_utc"), NotNull]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the time that the audit was created
        /// </summary>
        [Column("crt_utc"), NotNull, AutoGenerated]
        public DateTime CreationTime { get; set; }

        /// <summary>
        /// Gets or sets the session key
        /// </summary>
        [Column("ses_id"), ForeignKey(typeof(DbAuditSession), nameof(DbAuditSession.Key))]
        public Guid SessionKey { get; set; }

        /// <summary>
        /// Gets or sets the process name
        /// </summary>
        [Column("ps_name")]
        public String ProcessName { get; set; }

        /// <summary>
        /// Gets or sets the process id
        /// </summary>
        [Column("ps_id")]
        public String ProcessId { get; set; }


    }
}
