using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents a mapping between a participant and an audit
    /// </summary>
    [Table("aud_ptcpt_aud_assoc_tbl")]
    public class DbAuditParticipantAuditAssociation  : DbIdentified
    {

        /// <summary>
        /// Gets or sets the key 
        /// </summary>
        [PrimaryKey, Column("assoc_id"), AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the audit
        /// </summary>
        [Column("aud_id"), ForeignKey(typeof(DbAudit), nameof(DbAudit.Key))]
        public Guid AuditKey { get; set; }

        /// <summary>
        /// Gets or sets the participant
        /// </summary>
        [Column("ptcpt_id"), ForeignKey(typeof(DbAuditParticipant), nameof(DbAuditParticipant.Key))]
        public Guid ParticipantKey { get; set; }

        /// <summary>
        /// True if the user is requestor
        /// </summary>
        [Column("is_rqo")]
        public bool IsRequestor { get; set; }

    }
}
