/*
 * Copyright 2015-2018 Mohawk College of Applied Arts and Technology
 *
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 * User: justin
 * Date: 2018-10-27
 */
using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an actor in the db for audits
    /// </summary>
    [Table("aud_ptcpt_tbl")]
    [AssociativeTable(typeof(DbAuditCode), typeof(DbAuditParticipantRoleAssocation))]
    public class DbAuditParticipant : DbIdentified
    {
        /// <summary>
        /// Gets or sets the key of the participant
        /// </summary>
        [Column("ptcpt_id"), PrimaryKey, AutoGenerated]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the node key
        /// </summary>
        [Column("node_id"), ForeignKey(typeof(DbAuditNode), nameof(DbAuditNode.Key))]
        public Guid NodeKey { get; set; }

        /// <summary>
        /// Gets or sets the security identifier
        /// </summary>
        [Column("sid")]
        public Guid SecurityIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the user id
        /// </summary>
        [Column("usr_id")]
        public String UserIdentifier { get; set; }

        /// <summary>
        /// Gets or sets the user name
        /// </summary>
        [Column("usr_name")]
        public String UserName { get; set; }

        /// <summary>
        /// Gets or sets the network access point
        /// </summary>
        [Column("net_ap")]
        public String NetworkAccessPoint { get; set; }

        /// <summary>
        /// Network access point type
        /// </summary>
        [Column("net_ap_typ")]
        public Int32 NetworkAccessPointType { get; set; }
    }
}
