using SanteDB.OrmLite.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SanteGuard.Persistence.Ado.Data.Model
{
    /// <summary>
    /// Represents an audit node in the database
    /// </summary>
    [Table("aud_nod_tbl")]
    public class DbAuditNode : DbNonVersionedBaseData
    {
        /// <summary>
        /// Gets or sets the key
        /// </summary>
        [Column("node_id"), AutoGenerated, NotNull, PrimaryKey]
        public override Guid Key { get; set; }

        /// <summary>
        /// Gets or sets the device
        /// </summary>
        [Column("dev_id")]
        public Guid? DeviceKey { get; set; }

        /// <summary>
        /// Gets or sets the name of the node
        /// </summary>
        [Column("name")]
        public String Name { get; set; }

        /// <summary>
        /// Gets or sets the host name
        /// </summary>
        [Column("host_name")]
        public String HostName { get; set; }

        /// <summary>
        /// Gets or sets the status code
        /// </summary>
        [Column("sts_cd_id"), NotNull]
        public int StatusCode { get; set; }
    }
}
